<?xml version="1.0"?>
<robot name="sentry" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ghost_sim)/urdf/macros/actuator_macros.xacro" />
  <xacro:include filename="$(find ghost_sim)/urdf/macros/sensor_macros.xacro" />

  <!-- Import Primary Robot URDF -->
  <xacro:include filename="$(find ghost_description)/urdf_robomasters/sentry.xacro" />

  <!-- Add Sensors -->
  <xacro:lidar_macro link_name="lidar_link" topic_name="scan"></xacro:lidar_macro>
  <!-- <xacro:imu_macro parent_link="camera_view_link"></xacro:imu_macro> -->

  <!-- Add Mecanum -->
  <!-- https://github.com/qaz9517532846/gazebo_mecanum_plugins/tree/ros2-foxy -->
  <gazebo>
    <plugin name="gazebo_ros_joint_state_publisher"
      filename="libgazebo_ros_joint_state_publisher.so">
      <update_rate>100</update_rate>
      <joint_name>base_back_left_wheel_joint</joint_name>
      <joint_name>base_front_left_wheel_joint</joint_name>
      <joint_name>base_front_right_wheel_joint</joint_name>
      <joint_name>base_back_right_wheel_joint</joint_name>
    </plugin>

    <plugin name="mecanum_plugin" filename="libmecanum_plugin.so">
      <LeftBack>base_back_left_wheel_joint</LeftBack>
      <LeftFront>base_front_left_wheel_joint</LeftFront>
      <RightFront>base_front_right_wheel_joint</RightFront>
      <RightBack>base_back_right_wheel_joint</RightBack>
      <BaseLink>base_link</BaseLink>
      <WheelRadius>${mecanum_diameter/2}</WheelRadius>
      <LeftRightSeperation>${2*x_dist_to_wheel}</LeftRightSeperation>
      <FrontBackSeperation>${2*y_dist_to_wheel}</FrontBackSeperation>
      <x_stddev>0.05</x_stddev>
      <y_stddev>0.05</y_stddev>
      <r_stddev>0.03</r_stddev>
    </plugin>

    <plugin name="object_controller" filename="libgazebo_ros_planar_move.so">
      <commandTopic>mecanum_vel</commandTopic>
      <publish_odom_tf>false</publish_odom_tf>
      <publish_odom>false</publish_odom>
      <robotBaseFrame>base_footprint</robotBaseFrame>
    </plugin>
  </gazebo>
</robot>